<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>BlankInputs</description>
   <name>EmailBlankInputs</name>
   <tag></tag>
   <elementGuidId>ad082943-8a09-4fb1-b47d-38347607b921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']//div[1]//label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
