<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>PasswordBlankInputs</description>
   <name>PasswordBlankInputs</name>
   <tag></tag>
   <elementGuidId>42b9b818-007e-4bf3-a562-d0da3838b953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']//div[2]//label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
