<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Painting1</name>
   <tag></tag>
   <elementGuidId>fbfe5350-c7c6-4cd8-8fc1-c9241395df4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;demo&quot;)/div[@class=&quot;card-wrap&quot;]/article[@class=&quot;card white-panel&quot;]/div[@class=&quot;description&quot;]/div[@class=&quot;about&quot;]/p[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[contains(text(),'Painting123')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Painting1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo&quot;)/div[@class=&quot;card-wrap&quot;]/article[@class=&quot;card white-panel&quot;]/div[@class=&quot;description&quot;]/div[@class=&quot;about&quot;]/p[1]</value>
   </webElementProperties>
</WebElementEntity>
