<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Painting</description>
   <name>serviceName</name>
   <tag></tag>
   <elementGuidId>54cbec3b-6932-44b0-b587-bd521f6f2a96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[contains(text(),'Painting1')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
