<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>imageUpload3</description>
   <name>imageUpload3</name>
   <tag></tag>
   <elementGuidId>4e2cb7d0-89b0-4a1c-b84f-df9527bba76d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='img_up_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
