<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Material</description>
   <name>Material</name>
   <tag></tag>
   <elementGuidId>2028ad94-61da-4f56-83bc-f77d237c0948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='section']//div[7]//div[2]//label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
