<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Price</description>
   <name>Price</name>
   <tag></tag>
   <elementGuidId>e3b0e6f1-0ad7-4682-a66e-ddedda8d923e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='section']//div[6]//div[2]//label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
